export const mockUser = {
  id: "user_1",
  name: "John Doe",
  email: "demo@devstash.io",
  isPro: false,
  createdAt: new Date("2024-01-01"),
  updatedAt: new Date("2024-01-15"),
};

export const mockItemTypes = [
  {
    id: "type_snippet",
    name: "snippet",
    icon: "Code",
    color: "#3b82f6",
    isSystem: true,
  },
  {
    id: "type_prompt",
    name: "prompt",
    icon: "Sparkles",
    color: "#8b5cf6",
    isSystem: true,
  },
  {
    id: "type_command",
    name: "command",
    icon: "Terminal",
    color: "#f97316",
    isSystem: true,
  },
  {
    id: "type_note",
    name: "note",
    icon: "StickyNote",
    color: "#fde047",
    isSystem: true,
  },
  {
    id: "type_file",
    name: "file",
    icon: "File",
    color: "#6b7280",
    isSystem: true,
  },
  {
    id: "type_image",
    name: "image",
    icon: "Image",
    color: "#ec4899",
    isSystem: true,
  },
  {
    id: "type_link",
    name: "link",
    icon: "Link",
    color: "#10b981",
    isSystem: true,
  },
];

export const mockCollections = [
  {
    id: "col_1",
    name: "React Patterns",
    description: "Common React patterns and hooks",
    isFavorite: true,
    itemCount: 12,
    dominantTypeId: "type_snippet",
    typeIds: ["type_snippet", "type_file", "type_link"],
  },
  {
    id: "col_2",
    name: "Python Snippets",
    description: "Useful Python code snippets",
    isFavorite: false,
    itemCount: 8,
    dominantTypeId: "type_snippet",
    typeIds: ["type_snippet", "type_note"],
  },
  {
    id: "col_3",
    name: "Context Files",
    description: "AI context files for projects",
    isFavorite: true,
    itemCount: 5,
    dominantTypeId: "type_file",
    typeIds: ["type_file", "type_note"],
  },
  {
    id: "col_4",
    name: "Interview Prep",
    description: "Technical interview preparation",
    isFavorite: false,
    itemCount: 24,
    dominantTypeId: "type_note",
    typeIds: ["type_note", "type_snippet", "type_link", "type_prompt"],
  },
  {
    id: "col_5",
    name: "Git Commands",
    description: "Frequently used git commands",
    isFavorite: true,
    itemCount: 15,
    dominantTypeId: "type_command",
    typeIds: ["type_command", "type_file"],
  },
  {
    id: "col_6",
    name: "AI Prompts",
    description: "Curated AI prompts for coding",
    isFavorite: false,
    itemCount: 18,
    dominantTypeId: "type_prompt",
    typeIds: ["type_prompt", "type_snippet", "type_file"],
  },
];

export const mockItems = [
  {
    id: "item_1",
    title: "useAuth Hook",
    description: "Custom authentication hook for React applications",
    contentType: "TEXT" as const,
    content: `import { useState, useEffect } from 'react';\n\nexport function useAuth() {\n  const [user, setUser] = useState(null);\n  const [loading, setLoading] = useState(true);\n\n  useEffect(() => {\n    // fetch session\n  }, []);\n\n  return { user, loading };\n}`,
    language: "typescript",
    isFavorite: true,
    isPinned: true,
    itemTypeId: "type_snippet",
    tags: ["react", "auth", "hooks"],
    createdAt: new Date("2026-01-15"),
  },
  {
    id: "item_2",
    title: "API Error Handling Pattern",
    description: "Fetch wrapper with exponential backoff retry logic",
    contentType: "TEXT" as const,
    content: `async function fetchWithRetry(url: string, retries = 3) {\n  for (let i = 0; i < retries; i++) {\n    try {\n      const res = await fetch(url);\n      if (!res.ok) throw new Error(res.statusText);\n      return res.json();\n    } catch (e) {\n      if (i === retries - 1) throw e;\n      await new Promise(r => setTimeout(r, 2 ** i * 1000));\n    }\n  }\n}`,
    language: "typescript",
    isFavorite: false,
    isPinned: true,
    itemTypeId: "type_snippet",
    tags: ["api", "error-handling", "fetch"],
    createdAt: new Date("2026-01-12"),
  },
  {
    id: "item_3",
    title: "ChatGPT Code Review Prompt",
    description: "System prompt for thorough code review",
    contentType: "TEXT" as const,
    content:
      "You are an expert code reviewer. Review the following code for correctness, performance, security, and maintainability. Provide specific, actionable feedback.",
    language: null,
    isFavorite: true,
    isPinned: false,
    itemTypeId: "type_prompt",
    tags: ["chatgpt", "code-review"],
    createdAt: new Date("2026-01-10"),
  },
  {
    id: "item_4",
    title: "Git branch cleanup",
    description: "Delete all merged local branches",
    contentType: "TEXT" as const,
    content:
      "git branch --merged | grep -v '\\*\\|main\\|master' | xargs -n 1 git branch -d",
    language: "bash",
    isFavorite: false,
    isPinned: false,
    itemTypeId: "type_command",
    tags: ["git", "cleanup"],
    createdAt: new Date("2026-01-08"),
  },
  {
    id: "item_5",
    title: "Tailwind CSS Cheatsheet",
    description: "Quick reference for Tailwind utility classes",
    contentType: "URL" as const,
    url: "https://tailwindcss.com/docs",
    isFavorite: false,
    isPinned: false,
    itemTypeId: "type_link",
    tags: ["tailwind", "css", "reference"],
    createdAt: new Date("2026-01-05"),
  },
];

export const mockTypeCounts: Record<string, number> = {
  type_snippet: 24,
  type_prompt: 18,
  type_command: 15,
  type_note: 12,
  type_file: 5,
  type_image: 3,
  type_link: 8,
};
